name: complex

on:
  push:
    branches-ignore:
      - rc-*
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  actions: write

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date +%Y-%m-%d
  
  macos:  
    runs-on: macos-latest
    steps:
      - run: date

  depends:
    runs-on: ubuntu-latest
    needs: [ubuntu, macos]
    steps:
    - run: echo "All jobs are done"

  trigger-manual:
    name: Trigger manual action
    needs: depends
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v4
      - name: run-workflow
        uses: lordlive/custom-action/trigger@v1.0.7
        with:
          workflow-ref: ${{ github.ref_name }}
          workflow-path: .github/workflows/manual.yml
          build-version: v1.1.0
