name: complex

on:
  push:
    branches:
      - rc-*
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date +%Y-%m-%d

  windows:
    runs-on: windows-latest
    steps:
      - run: date
    
  macos:  
    runs-on: macos-latest
    steps:
      - run: date

  depends:
    runs-on: ubuntu-latest
    needs: [ubuntu, macos, windows]
    steps:
    - run: echo "All jobs are done"

  trigger-manual:
    name: Trigger manual action
    needs: depends
    uses: lordlive/custom-action/trigger
    with:
      workflow-ref: ${{ github.ref_name }}
      workflow-path: .github/workflows/manual.yml
      build-version: ""
