name: manual
on:
  workflow_dispatch:
    inputs:
      build-version:
        description: 'Build version'
        required: false
        default: 'v1.0.0'

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a manually triggered workflow from ${{ github.ref_name }}"
      - run: echo "Build version is ${{ github.event.inputs.build-version }}"
