name: use-workflow

on:
  push:
    branches:
      - rc-*
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  trigger-manual:
    name: Trigger manual action
    uses: lordlive/standart-workflows/.github/workflows/trigger.yml@rc-1.0.0
    with:
      workflow-ref: rc-1.0.0
      workflow-path: .github/workflows/manual.yml
      build-version: v1.1.0
