name: use-workflow

on:
  push:
    branches:
      - rc-*
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  trigger-manual:
    name: Trigger manual action
    uses: lordlive/standart-workflows/.github/workflows/trigger.yml@rc-1.0.0
    secrets: inherit
    with:
      workflow-ref: ${{ github.ref_name }}
      workflow-path: .github/workflows/manual.yml
      build-version: v1.1.0
